### ISSUE TITLE
formal proofs for blockchain code correctness

### ISSUE THREAD

**Issue by mycall** [Azure/azure-blockchain-projects#16]
In the wake of the Ethereum DOA failure, I request the RISE Working Group on Formal Methods (and Leslie Lamport) @ Microsoft Research to analyze this project's code for any hidden problems.  They have a vast amount of knowledge in testing code, on a different level and typical testing, and would be the best fit to protect developer's investments into this platform.

**Comment by gregmisiorek** [comment]
@mycall which project code are you referring to? i don't see anything here on github. unless the code is evaluated by the community there is no way to know what problems exist if any. for many DAO problems are an opportunity to improve and not to put the nail to the coffin.
