### ISSUE TITLE
UXTO instead of UTXO

### ISSUE THREAD

**Issue by stembrain** [Azure/azure-blockchain-projects#17]
There are a couple of passages in the white paper markdown that refer to UXTO as well as UTXO. It seems like all the references should be to "UTXO". If UXTO is also a valid term then maybe a foot note about the difference between the two would be helpful.

**Comment by marleyg** [comment]
Fixed, Typo thanks

**Comment by DavidBurela** [comment]
Flag as closed?

**Comment by stembrain** [comment]
Seems like it
