### ISSUE TITLE
Uanbel to deploy BaaS template

### ISSUE THREAD

**Issue by arturoqu** [Azure/azure-blockchain-projects#19]
I get this error:

StatusMessage

{
  "error": {
    "code": "MissingRequiredProperties",
    "message": "One of the following properties must be specified: WeeklyRecurrence, DailyRecurrence, HourlyRecurrence."
  }
}

•

Resource

BaaSDevTestLab1/LabVmsShutdown

**Comment by arturoqu** [comment]
**This is the detialed information that I get when I tried to deploy it, the one about the credentials is fine but the other errors aredefinitely about missing pieces in the template..**

At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. (Code: DeploymentFailed)
 •The URI and/or credentials could not be validated successfully. (Code: IncorrectClientCredentialOrCollectionUri)

•One of the following properties must be specified: WeeklyRecurrence, DailyRecurrence, HourlyRecurrence. (Code: MissingRequiredProperty)

•Property 'threshold' should be a Json Array with a minimum of 0 elements, like "['Basic_A0']. (Code: JsonArrayWithMinCount)

•Property 'threshold' should be a Json Array with a minimum of 0 elements, like "['Basic_A0']. (Code: JsonArrayWithMinCount)

**Comment by DavidBurela** [comment]
I have the same issue when I try to deploy the BaaS template listed on https://github.com/Azure/azure-blockchain-projects/tree/master/baas-template

![image](https://cloud.githubusercontent.com/assets/1320729/16651922/5ed6ff64-448a-11e6-803b-2fc6085b26b6.png)

@marleyg is there someone we need to ping to get this fixed?

**Comment by marleyg** [comment]
Sorry, removing that old version.  The new version is releasing soon.

**Comment by arturoqu** [comment]
Thank you...the logical question is, do you have an ETA?

I do a lot of customer demos and this is one thing that is in my mandate to do...

Thanks...

**Comment by marleyg** [comment]
You need a completely scripted multi-node private Blockchain lab?  If so, next week.  You can create nose by node in a non-scripted Dev-test lab now.
