### ISSUE TITLE
geth --genesis doesn't exist any more

### ISSUE THREAD

**Issue by flexray** [Azure/azure-blockchain-projects#24]
geth --genesis lab-seed.json doesn't work with the latest geth, tested on Ubuntu 14.04 and 16.04. Thus seeding is not working.

**Comment by marleyg** [comment]
The Go Homestead release artifact's geth settings use the new init:

geth  --rpc --rpcport "8080" --rpccorsdomain "*"  --port "2402" --ipcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --rpcapi "db,eth,net,web3" --networkid 1001201 --datadir "chains/devtest" init lab-seed.json

geth --datadir chains/devtest
