### ISSUE TITLE
Suggest removal of link in README.md

### ISSUE THREAD

**Issue by bcbrock** [Azure/azure-blockchain-projects#38]
The README.md file contains the following link:

https://www.reddit.com/r/btc/comments/4p0gq3/why_turingcomplete_smart_contracts_are_doomed/

I would suggest removing this link from your project page for two reasons. First, the author of this post appears to be unqualified in the field. The post seems to be predicted on the belief that (and I quote)
```
Only non-Turing-complete languages support formal reasoning and verification
```
This is simply not true. By linking to this post your project implicitly affirms that it is based on this faulty premise. 

One could also argue that this link indirectly violates your Code of Conduct, as the author uses language that is quite insulting, stating that for [most programmers]
```
Their understanding of computing is childish, naïve, and simplistic
```

There are many good arguments to be made for reduced-function blockchain languages. I'm certain you can find a more reasoned and factually correct references to the underlying issues than this post.

**Comment by marleyg** [comment]
Removed, thanks.
