### ISSUE TITLE
How use cryptlet?

### ISSUE THREAD

**Issue by DayronIG** [Azure/azure-blockchain-projects#54]
For me it's not clear how I can use the cryptlet, how can I start using them inside a consortium.

**Comment by marleyg** [comment]
The Cryptlet Framework is currently in private preview with a limited set of customers and partners.  However, once we get through this round of early adopters we will be releasing it in a broader preview program within Azure.   You will then be able to create an instance of the Cryptlet Framework and begin using and developing cryptlets as blockchain oracles and for contract or application logic.

**Comment by marleyg** [comment]
Closing, more details coming soon.

**Comment by DayronIG** [comment]
Tnks

**Comment by amrikmahal** [comment]
Hi, 
Eager to get hand on Cryptlets,  Please share the release dates, if available.

**Comment by marleyg** [comment]
Will do.  Expect to see some developer documentation and code this fall.

**Comment by tatigo** [comment]
Hello, is Cryptlet Framework available now?

**Comment by Daniel-Szego** [comment]
Hy all, 
I will be doing some Azure Blockchain presentations during the coming weeks, and well I would have basically the same question: is there coincidentally something that can shown to public ? Slides are always somehow boring :)

Thanks, 
 Regards, 
Daniel

**Comment by marleyg** [comment]
We will be releasing the Enterprise Smart Contracts and Cryptlet Framework on git soon...

**Comment by koalalorenzo** [comment]
"soon" :) Better than never

**Comment by sayedimac** [comment]
Happy days!

**Comment by swen002** [comment]
Any news on cryptlets?

**Comment by tina1998612** [comment]
Any update on cryplets? thanks!
