### ISSUE TITLE
No applications found - Azure Blockchain workbench

### ISSUE THREAD

**Issue by yieniggu** [Azure/azure-blockchain-projects#68]
Yesterday I created a new blockchain workbench guided by the docs on: https://docs.microsoft.com/en-us/azure/blockchain/workbench/deploy

The main issue is when am going to the web app, since I can't see anything, it only shows: No applications found, Contact the Workbench administrator to get access to an application.

Funny thing is that I added a user to work along with me (both propietaries and admins). He can acces to the resource and create apps. Also he can see me as a member (i only see me). Another thing to add is that he created a contract, which appears to me in the workbench and lets me to take actions on any instance of the contract (permitted by the role ive been given).

How did i lose (if) my privileges/permissions if i created the workbench?

**Comment by marleyg** [comment]
Can you re-post your question here: https://social.msdn.microsoft.com/Forums/en-US/home?forum=azureblockchain
